server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location /monthly-planning/ {
        try_files $uri $uri/ /monthly-planning/index.html;
    }

    location = / {
        return 302 $scheme://$http_host/monthly-planning/;
    }
}
